# Run like this: ansible-playbook uninstall.yml
#
# Ensure that you are not adding the latest version to list variable versions_to_uninstall.
- name: Uninstall old versions of Hortonworks/Cloudera software. 
  hosts: all:localhost
  become: true
  gather_facts: false
  vars:
    # Retrieve like this: yum repolist
    repos_to_uninstall:
      # Real HDP repos.
      # - HDP-3.1-repo-201
      # - HDP-3.1-repo-251
      # - HDP-3.1-repo-301
      # - HDP-7.1-repo-351
      # To test with Docker (https://download.docker.com/linux/centos/docker-ce.repo) and rpmfusion repo.
      - docker-ce-stable
      - rpmfusion-free-updates

  tasks:
  - name: Install yumdb 
    yum:
      name: yum-utils
      state: present

  - name: Get list of installed packages from repo 
    shell: "yumdb search from_repo repoid '{{ item }}' --noplugins | grep -v '^$' | grep -v '^ ' | sort"
    changed_when: false
    register: packages_to_uninstall
    loop: "{{ repos_to_uninstall }}"

  - name: Print packages to uninstall
    debug: 
      msg: "{{ item.stdout_lines }}"
    loop: "{{ packages_to_uninstall.results }}"

  # - name: Uninstall packages
  #   yum:
  #     name: "{{ packages_to_uninstall.stdout_lines }}"
  #     state: absent  
