# Run like this: ansible-playbook -v uninstall.yml
#
# When testing. Restore packages like this:
#  dnf install -y adobe-mappings-cmap-20171205-4.fc29.noarch
- name: Uninstall old versions of Hortonworks/Cloudera software. 
  hosts: all:localhost
  become: true
  vars:
    packages_to_uninstall:
      - 'tez'
      - 'tez_hive2'
      - 'zookeeper'
    versions_to_uninstall:
      - '2_5_3_0_37'
      - '2_6_0_3_8'
      - '2_6_5_0_292'
      - '2_6_5_1175_1'
      - '3_1_5_0_152'
      - '3_1_5_6123_1'
      - '3_1_5_6157_1'
    packages_and_versions_list: []

  tasks:
  - name: Build list of packages to uninstall
    set_fact:
      packages_and_versions_list: "{{ packages_and_versions_list + [ item.0 + '_' + item.1 + '*' ] }}"
    loop: "{{ packages_to_uninstall|product(versions_to_uninstall)|list }}"

  - name: Add test package to list
    set_fact:
      packages_and_versions_list: "{{ packages_and_versions_list + [ 'adobe-mappings-cmap-20171205-4.fc29*' ] }}"

  - name: Print packages to uninstall
    debug:
      var: packages_and_versions_list

  - name: Uninstall packages
    yum:
      name: "{{ packages_and_versions_list }}"
      state: absent  
